---
- hosts: all
  become: yes
  vars:
    username: "contest"
    new_password: "ChangeMe123!"
  tasks:
    - name: Fail if username or new_password is not provided
      fail:
        msg: "Please provide both 'username' and 'new_password'. Example: ansible-playbook -i inventory.ini -K change_password.yml -e 'username=contest new_password=MyPassword123'"
      when: username == "" or new_password == ""

    - name: Change password for target user
      user:
        name: "{{ username }}"
        password: "{{ new_password | password_hash('sha512') }}"
        update_password: always
