- hosts: all
  become: yes
  vars:
    username: contest
  tasks:
    - name: Remove user '{{ username }}' and its home directory
      user:
        name: "{{ username }}"
        state: absent
        remove: yes
        force: yes
