- hosts: lab
  become: yes
  tasks:
    - name: Copy site blocking script
      copy:
        src: site_blocking.sh
        dest: /tmp/site_blocking.sh
        mode: '0755'

    - name: Run site_blocking script
      command: /tmp/site_blocking.sh