- hosts: all
  become: yes
  tasks:
    - name: Ensure silent screenshot tools are installed
      package:
        name:
          - scrot
          - gnome-screenshot
          - imagemagick
          - grim
          - ffmpeg
        state: present

    - name: Copy start_screenshot script to protected system path
      copy:
        src: start_screenshot.sh
        dest: /usr/local/bin/start_screenshot.sh
        mode: '0755'

    - name: Run start_screenshot script
      command: /usr/local/bin/start_screenshot.sh
